server:
  port: 8082

spring:
  application:
    name: 'KoFee'
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  liquibase:
    url: 'jdbc:postgresql://localhost:5433/kofee'
    user: 'postgres'
    password: 'postgres'
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5433/kofee'
    username: 'postgres'
    password: 'postgres'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8083/realms/kofee'
