server:
  port: 8082

spring:
  application:
    name: KoFee
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/kofee
