server:
  port: 8082

spring:
  application:
    name: 'KoFee'
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    bootstrap-servers: 'localhost:9092'
    properties:
      schema.registry.url: 'http://localhost:8084'
    producer:
      client-id: 'kofee-${random.uuid}'
      transaction-id-prefix: 'kofee-${random.uuid}'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      client-id: 'kofee-${random.uuid}'
      group-id: 'local-kofee'
      auto-offset-reset: 'earliest'
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        specific.avro.reader: true
        # Delegate deserializers
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
  liquibase:
    url: 'jdbc:postgresql://localhost:5433/kofee'
    user: 'postgres'
    password: 'postgres'
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'
  r2dbc:
    url: 'r2dbc:postgresql://localhost:5433/kofee'
    username: 'postgres'
    password: 'postgres'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8083/realms/kofee'
  threads:
    virtual:
      enabled: true
